server:
    port: 8081
    
  
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/hospital
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      format_sql: true
      generate_statistics: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      
    application:
      name: Hospital-Details
logging.level.org.hibernate.stat: debug
logging.level.org.hibernate.type: trace
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.generate_statistics: true
spring.jpa.show-sql: true